#!/bin/sh

# Add keyd to groups
groupadd keyd

# Enable keyd service
systemctl enable keyd.service

# use systemd-detect-virt to detect if in chroot -> if not in chroot, set keymap and start keyd
# systemd-detect-virt -r returns 1 if not in a chroot
systemd-detect-virt -r || /usr/lib/eupnea/set-keymap --automatic && systemctl start keyd.service
