#!/bin/sh

# Add keyd to groups
groupadd keyd

# Enable and start keyd service if not in a chroot
systemctl enable keyd.service
systemd-detect-virt -r || systemctl start keyd.service # systemd-detect-virt -r returns 1 if not in a chroot
