#!/bin/sh

# Add keyd to groups
groupadd keyd

# Enable and start keyd service if not in a chroot
if [ -f /proc/mounts ]; then systemctl enable --now keyd.service; else systemctl enable keyd.service; fi
