#!/bin/sh

# Enable and start touchscreen fix service if not in a chroot
systemctl enable touchscreen-fix.service
systemd-detect-virt -r || systemctl start touchscreen-fix.service # systemd-detect-virt -r returns 1 if not in a chroot
